import type { RawObservation } from "@/lib/discovery/types";

/**
 * In-memory QA records only. Do not insert these into the database.
 * Every record is marked isTest so publication stays closed.
 */
export const DISCOVERY_FIXTURES: RawObservation[] = [
  event({
    title: "Saturday Amateur Open",
    eventType: "TOURNAMENT",
    startDate: "2026-10-17",
    endDate: "2026-10-17",
    countryCode: "lt",
    city: "Vilnius",
    venue: "SEB Arena",
    timezone: "Europe/Vilnius",
    surface: "hard",
    indoorOutdoor: "indoor",
    originalLevel: "Intermediate",
    gender: "open",
    organiser: "Vilnius Tennis Club",
    officialEventUrl: "https://example.com/lt/saturday-amateur",
    registrationUrl: "https://example.com/lt/saturday-amateur/register",
    registrationStatus: "open",
    priceAmount: 25,
    currency: "EUR",
    latitude: 54.6872,
    longitude: 25.2797,
    sourceName: "Vilnius Tennis Club",
    sourceUrl: "https://example.com/lt/saturday-amateur",
    sourceType: "club",
  }),
  event({
    title: "Riga One Day Cup",
    startDate: "2026-10-24",
    countryCode: "lv",
    city: "Riga",
    timezone: "Europe/Riga",
    surface: "clay",
    indoorOutdoor: "outdoor",
    originalLevel: "Amateur",
    currency: "EUR",
    priceAmount: 20,
    organiser: "Riga Tennis Centre",
    officialEventUrl: "https://example.com/lv/riga-cup",
    sourceName: "Riga Tennis Centre",
    sourceUrl: "https://example.com/lv/riga-cup",
    sourceType: "tennis_centre",
    latitude: 56.9496,
    longitude: 24.1052,
  }),
  event({
    title: "Barcelona Weekend Open",
    startDate: "2026-11-07",
    endDate: "2026-11-08",
    countryCode: "es",
    region: "Catalonia",
    city: "Barcelona",
    timezone: "Europe/Madrid",
    surface: "clay",
    indoorOutdoor: "outdoor",
    originalLevel: "Advanced",
    gender: "men",
    currency: "EUR",
    priceAmount: 40,
    organiser: "Barcelona Tennis",
    officialEventUrl: "https://example.com/es/barcelona-open",
    registrationUrl: "https://example.com/es/barcelona-open/enter",
    registrationStatus: "coming soon",
    sourceName: "Barcelona Tennis",
    sourceUrl: "https://example.com/es/barcelona-open",
    sourceType: "tournament_organiser",
    latitude: 41.3874,
    longitude: 2.1686,
  }),
  event({
    title: "Stockholm Women Amateur",
    eventType: "TOURNAMENT",
    startDate: "2026-11-14",
    countryCode: "se",
    city: "Stockholm",
    timezone: "Europe/Stockholm",
    surface: "hard",
    indoorOutdoor: "indoor",
    originalLevel: "Intermediate",
    gender: "women",
    currency: "SEK",
    priceAmount: 350,
    organiser: "Stockholm Tennis",
    officialEventUrl: "https://example.com/se/stockholm-women",
    registrationStatus: "open",
    sourceName: "Stockholm Tennis",
    sourceUrl: "https://example.com/se/stockholm-women",
    sourceType: "club",
    latitude: 59.3293,
    longitude: 18.0686,
  }),
  event({
    title: "Berlin Club Competition",
    eventType: "CLUB_COMPETITION",
    startDate: "2026-10-31",
    endDate: "2026-11-01",
    countryCode: "de",
    city: "Berlin",
    timezone: "Europe/Berlin",
    surface: "carpet",
    indoorOutdoor: "indoor",
    originalLevel: "D-level",
    currency: "EUR",
    priceAmount: 30,
    organiser: "Berlin Tennis Club",
    officialEventUrl: "https://example.com/de/berlin-club",
    registrationStatus: "full",
    sourceName: "Berlin Tennis Club",
    sourceUrl: "https://example.com/de/berlin-club",
    sourceType: "club",
    latitude: 52.52,
    longitude: 13.405,
  }),
  event({
    title: "London Senior Afternoon",
    eventType: "PLAY_SESSION",
    startDate: "2026-12-05",
    countryCode: "gb",
    city: "London",
    timezone: "Europe/London",
    surface: "grass",
    indoorOutdoor: "outdoor",
    originalLevel: "Open",
    gender: "mixed",
    ageGroup: "40+",
    currency: "GBP",
    priceAmount: 15,
    organiser: "London Tennis Club",
    officialEventUrl: "https://example.com/gb/london-senior",
    registrationStatus: "closed",
    sourceName: "London Tennis Club",
    sourceUrl: "https://example.com/gb/london-senior",
    sourceType: "club",
    latitude: 51.5074,
    longitude: -0.1278,
  }),
  event({
    title: "Austin NTRP Match Day",
    eventType: "MATCH_DAY",
    startDate: "2026-11-21",
    countryCode: "us",
    region: "Texas",
    city: "Austin",
    timezone: "America/Chicago",
    surface: "hard",
    indoorOutdoor: "outdoor",
    originalLevel: "NTRP 3.5",
    currency: "USD",
    priceAmount: 35,
    organiser: "Austin Tennis Center",
    officialEventUrl: "https://example.com/us/austin-ntrp",
    sourceName: "Austin Tennis Center",
    sourceUrl: "https://example.com/us/austin-ntrp",
    sourceType: "tennis_centre",
    latitude: 30.2672,
    longitude: -97.7431,
  }),
  event({
    title: "Melbourne Junior Morning",
    eventType: "TOURNAMENT",
    startDate: "2026-12-12",
    countryCode: "au",
    city: "Melbourne",
    timezone: "Australia/Melbourne",
    surface: "hard",
    indoorOutdoor: "outdoor",
    originalLevel: "Beginner",
    gender: "boys",
    ageGroup: "U12",
    currency: "AUD",
    priceAmount: 20,
    organiser: "Melbourne Tennis",
    officialEventUrl: "https://example.com/au/melbourne-junior",
    registrationStatus: "unknown",
    sourceName: "Melbourne Tennis",
    sourceUrl: "https://example.com/au/melbourne-junior",
    sourceType: "club",
    latitude: -37.8136,
    longitude: 144.9631,
  }),
  event({
    title: "Tokyo Social Rally",
    eventType: "SOCIAL",
    startDate: "2026-11-03",
    countryCode: "jp",
    city: "Tokyo",
    timezone: "Asia/Tokyo",
    surface: "unknown",
    indoorOutdoor: "indoor",
    originalLevel: "ITN 6",
    currency: "JPY",
    priceAmount: 3000,
    organiser: "Tokyo Tennis Club",
    officialEventUrl: "https://example.com/jp/tokyo-social",
    sourceName: "Tokyo Tennis Club",
    sourceUrl: "https://example.com/jp/tokyo-social",
    sourceType: "club",
    latitude: 35.6762,
    longitude: 139.6503,
  }),
  event({
    title: "Hamburg Autumn Open",
    startDate: "2026-09-12",
    endDate: "2026-09-13",
    countryCode: "de",
    city: "Hamburg",
    timezone: "Europe/Berlin",
    surface: "clay",
    indoorOutdoor: "outdoor",
    currency: "EUR",
    priceAmount: 45,
    organiser: "Hamburg Tennis",
    officialEventUrl: "https://example.com/de/hamburg-autumn",
    registrationStatus: "closed",
    sourceName: "Hamburg Tennis",
    sourceUrl: "https://example.com/de/hamburg-autumn",
    sourceType: "tournament_organiser",
    latitude: 53.5511,
    longitude: 9.9937,
  }),
  event({
    title: "Vilnius Hit and Giggle",
    eventType: "SOCIAL",
    startDate: "2026-10-18",
    countryCode: "lt",
    city: "Vilnius",
    timezone: "Europe/Vilnius",
    organiser: "Vilnius Social Tennis",
    sourceName: "Facebook page",
    sourceUrl: "https://example.com/social/vilnius-hit",
    sourceType: "social_media",
  }),
];

export const DUPLICATE_SOURCE: RawObservation = event({
  title: "Saturday Amateur Open",
  startDate: "2026-10-17",
  countryCode: "lt",
  city: "Vilnius",
  venue: "SEB Arena",
  timezone: "Europe/Vilnius",
  organiser: "Vilnius Tennis Club",
  officialEventUrl: "https://example.com/lt/saturday-amateur",
  sourceName: "Tournament platform",
  sourceUrl: "https://example.com/platform/saturday-amateur",
  sourceType: "tournament_platform",
});

export const CONFLICTING_SOURCE: RawObservation = event({
  title: "Saturday Amateur Open",
  startDate: "2026-10-18",
  countryCode: "lt",
  city: "Vilnius",
  venue: "SEB Arena",
  timezone: "Europe/Vilnius",
  organiser: "Vilnius Tennis Club",
  sourceName: "Public calendar",
  sourceUrl: "https://example.com/calendar/saturday-amateur",
  sourceType: "public_calendar",
});

function event(input: Omit<RawObservation, "isTest">): RawObservation {
  return { ...input, isTest: true };
}
